# Test: HashiCorp Docker Mirror
FROM docker.mirror.hashicorp.services/datadog/agent:7.50.0 as datadog

FROM docker.mirror.hashicorp.services/amazon/aws-for-fluent-bit:2.34.3 as fluent-bit

# Example application
FROM alpine:latest
COPY --from=datadog /opt/datadog-agent /opt/datadog-agent
COPY --from=fluent-bit /fluent-bit /fluent-bit
