# Test: AWS ECR Public Registry
FROM public.ecr.aws/datadog/agent:7.77.0 as datadog

FROM public.ecr.aws/aws-observability/aws-for-fluent-bit:2.31.12 as fluent-bit

# Example application
FROM alpine:latest
COPY --from=datadog /opt/datadog-agent /opt/datadog-agent
COPY --from=fluent-bit /fluent-bit /fluent-bit
